function S08_evaluate_quality()
%% S08 - Evaluate reconstruction quality
% This module evaluates every reconstruction result that is currently
% available in results/.
%
% The manuscript metric policy is deliberately fixed across all methods:
%
%   metric image = double(image) / 255
%
% No clipping and no per-method normalization are applied before computing
% RMSE, NRMSE, PSNR, or SSIM.
%
% The absolute-error maps are retained in the original gray-level scale so
% that they can be used directly for the Section 8 spatial-error comparison.

config = section7_8_config();
addpath(config.functionsFolder);

referenceFile = fullfile(config.resultsFolder, 'reference_image.mat');
assert(exist(referenceFile, 'file') == 2, ...
    'Run S01_prepare_reference_image first.');

referenceData = load(referenceFile, 'Xref');
Xref = double(referenceData.Xref);

assert(exist('ssim', 'file') == 2, ...
    'MATLAB ssim was not found. Image Processing Toolbox is required.');

%% Describe the five reconstruction-result files
methods = struct( ...
    'name', { ...
        'Direct', ...
        'FDRI', ...
        'DCT-l1', ...
        'TVAL3', ...
        'TV-QC'}, ...
    'routeId', { ...
        'direct_separable_cpu', ...
        'fdri_cpu', ...
        'bpdn_dct_l1magic_cpu', ...
        'tval3_cpu', ...
        'tvqc_l1magic_cpu'}, ...
    'fileName', { ...
        'direct_reconstructions.mat', ...
        'fdri_reconstructions.mat', ...
        'dct_l1_reconstructions.mat', ...
        'tval3_reconstructions.mat', ...
        'tv_qc_reconstructions.mat'}, ...
    'stackField', { ...
        'directReconstructions', ...
        'fdriReconstructions', ...
        'dctL1Reconstructions', ...
        'tval3Reconstructions', ...
        'tvqcReconstructions'});

qualityTable = table();

errorMaps = struct();
errorMapSamplingPercentages = struct();

fprintf('\nS08 - Image-quality evaluation.\n');
fprintf('Metric scale: double(image)/255\n');
fprintf('Clipping before metrics: none\n');
fprintf('Per-method normalization: none\n\n');

for methodIndex = 1:numel(methods)
    method = methods(methodIndex);
    resultFile = fullfile(config.resultsFolder, method.fileName);

    if exist(resultFile, 'file') ~= 2
        fprintf('  %-7s: result file not present -> skipped\n', method.name);
        continue;
    end

    loaded = load(resultFile);

    assert(isfield(loaded, method.stackField), ...
        'Missing reconstruction stack in %s.', method.fileName);
    assert(isfield(loaded, 'samplingPercents') && ...
           isfield(loaded, 'Mvalues') && ...
           isfield(loaded, 'actualSamplingRatios'), ...
        'Sampling metadata is missing from %s.', method.fileName);

    reconstructionStack = double(loaded.(method.stackField));
    samplingPercents = double(loaded.samplingPercents(:));
    Mvalues = double(loaded.Mvalues(:));
    actualSamplingRatios = double(loaded.actualSamplingRatios(:));

    numberOfCases = numel(samplingPercents);
    assert(size(reconstructionStack, 3) == numberOfCases, ...
        'Reconstruction-stack length does not match sampling metadata.');

    methodErrorMaps = zeros([size(Xref), numberOfCases]);

    for r = 1:numberOfCases
        Xrecon = reconstructionStack(:, :, r);

        [metrics, absoluteErrorGray] = ...
            compute_section8_metrics(Xrecon, Xref);

        methodErrorMaps(:, :, r) = absoluteErrorGray;

        row = table( ...
            samplingPercents(r), ...
            samplingPercents(r) / 100, ...
            actualSamplingRatios(r), ...
            Mvalues(r), ...
            string(method.name), ...
            string(method.routeId), ...
            metrics.rmseNormalized, ...
            metrics.rmseGrayLevels, ...
            metrics.nrmseRelativeL2, ...
            metrics.psnrDb, ...
            metrics.ssim, ...
            metrics.ssimDynamicRange, ...
            metrics.metricScaleDivisor, ...
            metrics.clippingApplied, ...
            metrics.perMethodNormalizationApplied, ...
            'VariableNames', { ...
                'sampling_percentage', ...
                'nominal_sampling_ratio', ...
                'actual_sampling_ratio', ...
                'retained_measurements_M', ...
                'method', ...
                'route_id', ...
                'rmse_normalized', ...
                'rmse_gray_levels', ...
                'tutorial_nrmse_relative_l2', ...
                'psnr_section8_db', ...
                'ssim_section8', ...
                'ssim_dynamic_range', ...
                'metric_input_scale_divisor', ...
                'clipping_applied', ...
                'per_method_normalization_applied'});

        qualityTable = [qualityTable; row]; %#ok<AGROW>
    end

    errorMaps.(method.routeId) = methodErrorMaps;
    errorMapSamplingPercentages.(method.routeId) = samplingPercents;

    fprintf('  %-7s: evaluated %d reconstruction(s)\n', ...
        method.name, numberOfCases);
end

assert(height(qualityTable) > 0, ...
    'No reconstruction results were available for S08.');

qualityTable = sortrows(qualityTable, ...
    {'sampling_percentage', 'method'});

%% Save a reader-friendly CSV table
metricsCsv = fullfile(config.resultsFolder, ...
    'quality_metrics_generated.csv');
writetable(qualityTable, metricsCsv);

%% Save absolute-error maps for later figure generation
errorMapFile = fullfile(config.resultsFolder, ...
    'absolute_error_maps.mat');

save(errorMapFile, ...
    'errorMaps', 'errorMapSamplingPercentages');

fprintf('\nOutputs:\n');
fprintf('  %s\n', metricsCsv);
fprintf('  %s\n\n', errorMapFile);
end
